DRAFT = 'draft'
PUBLISHED = 'published'

PENDING = 'pending'
CONFIRMED = 'confirmed'
CANCELLED = 'cancelled'

RATING_MIN = 1
RATING_MAX = 5

ORDER_QUANTITY_MIN = 1
ORDER_QUANTITY_MAX = 100

SHOP_NAME_MAX_LENGTH = 200
PRODUCT_NAME_MAX_LENGTH = 200
PRODUCT_PRICE_MAX_DIGITS = 10
PRODUCT_PRICE_DECIMAL_PLACES = 2
