# Generated by Django 5.0.6 on 2026-07-24 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('user', 'User'), ('guest', 'Guest')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='RolePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(choices=[('users', 'Users'), ('shops', 'Shops'), ('products', 'Products'), ('orders', 'Orders'), ('reviews', 'Reviews')], max_length=50)),
                ('action', models.CharField(choices=[('read', 'Read'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=20)),
                ('scope', models.CharField(choices=[('all', 'All'), ('own', 'Own'), ('own_shop', 'Own Shop'), ('published', 'Published')], max_length=20)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='access_control.role')),
            ],
            options={
                'db_table': 'role_policies',
                'unique_together': {('role', 'resource', 'action')},
            },
        ),
    ]
